project_id = "lmsqashicqqgizrkbyjv"

[functions.card-payment-reminder]
verify_jwt = false

[functions.fixed-payment-reminder]
verify_jwt = false

[functions.installment-payment-reminder]
verify_jwt = false

[functions.loan-payment-reminder]
verify_jwt = false

[functions.financial-insights]
verify_jwt = false

[functions.financial-chat]
verify_jwt = false

[functions.receipt-scanner]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.admin-notification]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.family-invite]
verify_jwt = false

[functions.crypto-prices]
verify_jwt = false

[functions.new-user-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
